Models/Cidade.cs
namespace ProjetoCidades.Models
{
    public class Cidade
    {
        public int id { get; set; } 
        public string nome { get; set; }
        public string uf { get; set; }
        public int habitantes { get; set; }
        
    }
}

Models/ErrorViewModel.cs
using System;

namespace ProjetoCidades.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CidadesController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using ProjetoCidades.Models;
using ProjetoCidades.Repositorio;

namespace ProjetoCidades.Controllers
{
    public class CidadesController: Controller
    {
        CidadeRep cidaderep = new CidadeRep();
        public IActionResult Index()
        {
            var lista = cidaderep.Listar();
            return View(lista);
        }

        public IActionResult CidadesEstados()
        {
            var lista = cidaderep.Listar();
            return View(lista);
        }

        public IActionResult TodosDados()
        {
            var lista = cidaderep.Listar();
            return View(lista);
        }

        public IActionResult MaiorCidade()
        {
            var lista = cidaderep.Listar().OrderByDescending(x => x.habitantes).First();
            return View(lista);
        }

        public IActionResult MenorCidade()
        {
            var lista = cidaderep.Listar().OrderByDescending(x => x.habitantes).Last();
            return View(lista);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar([Bind] Cidade cidade)
        {
            cidaderep.Cadastrar(cidade);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            Cidade cidade = cidaderep.Listar().Where(x => x.id == id).FirstOrDefault();
            return View(cidade);
        }

        [HttpPost]
        public IActionResult Editar([Bind] Cidade cidade)
        {
            cidaderep.Editar(cidade);
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(Cidade cidade)
        {
            cidaderep.Excluir(cidade); 
            return RedirectToAction("Index");
        }

        public IActionResult Detalhes(int? id)
        {
            var cidade = cidaderep.Listar().Where(x => x.id == id).FirstOrDefault();
            return View(cidade);
        }
    

    }
}

Views/Cidades/Cadastrar.cshtml
@model ProjetoCidades.Models.Cidade

<div>
    <h2>Cadastrar</h2>
    <h4>Cidade</h4>
    <hr>
    <div class="row">
        <div class="col-md-4">
        <form asp-action="Cadastrar">
            <div asp.validation.summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control"/>
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="uf" class="control-label"></label>
                <input asp-for="uf" class="form-control"/>
                <span asp-validation-for="uf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="habitantes" class="control-label"></label>
                <input asp-for="habitantes" class="form-control"/>
                <span asp-validation-for="habitantes" class="text-danger"></span>
            </div>
            <div class = "form group">
                <input type="submit" value="Cadastrar" class="btn btn-default"/>
            </div>
        </form>
        </div>
        
    </div>
</div>

Views/Cidades/CidadesEstados.cshtml
@model IEnumerable<ProjetoCidades.Models.Cidade>
    <div>
    <h2> Minhas Cidades e seus Estados</h2>
     @{
        foreach(var item in Model)
        {
            <li>@item.nome, @item.uf</li>
        }
    }
</div>

Views/Cidades/Detalhes.cshtml
@model ProjetoCidades.Models.Cidade
<div>
    <h2>Detalhes da Cidade</h2>
    <p>
        <a asp-action="Index">Todas as Cidades</a>
    </p>

    <table class = "table">
        <thread>
            <tr>
                <th>ID</th>
                <th>Cidade</th>
                <th>UF</th>
                <th>Habitantes</th>
                <th></th>
            </tr>
        </thread>
        <tbody>
            @{
                <tr>
                    <td>
                        @Model.id
                    </td>
                    <td>
                        @Model.nome
                    </td>
                    <td>
                        @Model.uf
                    </td>
                    <td>
                        @Model.habitantes
                    </td>
                    <td>
                        <a asp-action="Editar" asp-route-id= "@Model.id"> Editar</a>
                        <a asp-action="Excluir" asp-route-id="@Model.id">Excluir</a>

                    </td>
                </tr>
                
            }
        </tbody>
    </table>
</div>

Views/Cidades/Editar.cshtml
@model ProjetoCidades.Models.Cidade

<div>
    <h2>Editar</h2>
    <h4>Cidade</h4>
    <hr>
    <div class="row">
        <div class="col-md-4">
        <form asp-action="Editar">
            <div asp.validation.summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control"/>
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="uf" class="control-label"></label>
                <input asp-for="uf" class="form-control"/>
                <span asp-validation-for="uf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="habitantes" class="control-label"></label>
                <input asp-for="habitantes" class="form-control"/>
                <span asp-validation-for="habitantes" class="text-danger"></span>
            </div>
            <div class = "form group">
                <input type="submit" value="Editar" class="btn btn-default"/>
            </div>
        </form>
        </div>
        
    </div>
</div>

Views/Cidades/Index.cshtml
@model IEnumerable<ProjetoCidades.Models.Cidade>
<div>
    <h2>Minhas Cidades</h2>
    <p>
        <a asp-action="Cadastrar">Cadastrar Nova Cidade</a>
    </p>

    <table class = "table">
        <thread>
            <tr>
                <th>ID</th>
                <th>Cidade</th>
                <th>UF</th>
                <th>Habitantes</th>
                <th></th>
            </tr>
        </thread>
        <tbody>
            @{
                foreach(var item in Model)
                {
                    <tr>
                        <td>
                            @item.id
                        </td>
                        <td>
                            @item.nome
                        </td>
                        <td>
                            @item.uf
                        </td>
                        <td>
                            @item.habitantes
                        </td>
                        <td>
                            <a asp-action="Editar" asp-route-id= "@item.id"> Editar</a>
                            <a asp-action="Detalhes" asp-route-id="@item.id">Detalhes</a>
                            <a asp-action="Excluir" asp-route-id="@item.id">Excluir</a>

                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Cidades/MaiorCidade.cshtml
@model ProjetoCidades.Models.Cidade
<div>
    <h2>
        Maior Cidade
    </h2>
    <li> @Model.nome, @Model.habitantes</li>
</div>

Views/Cidades/MenorCidade.cshtml
@model ProjetoCidades.Models.Cidade
<div>
    <h2>
        Menor Cidade
    </h2>
    <li> @Model.nome, @Model.habitantes</li>
</div>

Views/Cidades/TodosDados.cshtml
@model IEnumerable<ProjetoCidades.Models.Cidade>
<div>
    <h2> Todos os dados</h2>
    <table>
        <tr>
            <th>ID </th>
            <th>Nome </th>
            <th>Estado </th>
            <th>Habitantes </th>
        </tr>
    @{
        foreach (var item in Model)
        {
            <tr>
                <td>@item.id </td>
                <td>@item.nome </td>
                <td>@item.uf </td>
                <td>@item.habitantes </td>
            </tr>
        }
    }
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoCidades</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Cidades" asp-action="Index" class="navbar-brand">Projeto Cidades</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Cidades" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Cidades" asp-action="CidadesEstados">Cidades e Estados</a></li>
                    <li><a asp-area="" asp-controller="Cidades" asp-action="TodosDados">Todos os Dados</a></li>
                    <li><a asp-area="" asp-controller="Cidades" asp-action="MaiorCidade">Maior Cidade</a></li>
                    <li><a asp-area="" asp-controller="Cidades" asp-action="MenorCidade">Menor Cidade</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FF - ProjetoCidades</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>